Gopkg.lock, internal/common/minio.go, internal/millers/graph/graphkv.go
Allow non-gleaner metadata jsonld files to be milled
=> Allow openstack to be used as s3 store.

Makefile, scripts/minio2blaze.sh
This is for me, running on OS X, because docker build works better than podman on this platform.
=> Include docker tasks in Makefile

.gitignore, internal/summoner/acquire/acquire.go, internal/summoner/acquire/headlessNG.go, internal/summoner/acquire/resources.go, internal/summoner/sitemaps/sitemap_ng.go
- add DS_Store to .gitignore, for working on OS X
- Some more detailed logging, just to help me figure out what's going on (I'm totally okay with leaving this out if you'd prefer)
- Remove unused code from the headless browser code and do a couple todo's
- Make the headless browser retry getting json-ld if it fails to find it the first time
=> Implement retry in headless browser scenario

configs/template/GleanerConfig.md, internal/config/sources.go, pkg/cli/batch.go, pkg/cli/config.go, pkg/cli/gleaner.go, pkg/cli/init.go
add GleanerConfig.md to configuration directories
=> #47. run one source, fix init

configs/template/GleanerConfig.md, pkg/cli/config.go, pkg/cli/generate.go, pkg/cli/root.go
add GleanerConfig.md to configuration directories
=> #49. source maps fix

VERSION, docs/GleanerConfig.md, docs/README_Configure_Template.md, pkg/cli/config.go, pkg/cli/generate.go
fixes issue with glcon sources
=> Dv dev 63 fix sources

internal/summoner/acquire/acquire.go
I noticed a small inefficiency here while I was trying to figure out something else, but a tiny inefficiency during summoning might add up.
P.S. Merry Christmas! This isn't urgent. 🎄
=> Write the goquery so it gets only ld-json scripts

.idea/gleaner.iml, docs/SUMMARY.md, mkdocs.yml
Link to generated [docs](https://earthcube.github.io/geocodes_documentation/indexing/gleaner/)
=> Build docs for earthcube using mkdocs multirepo

go.mod, go.sum, internal/common/logger.go, internal/summoner/acquire/acquire.go, internal/summoner/acquire/headlessNG.go, pkg/cli/batch.go, pkg/cli/check.go, pkg/cli/config.go, pkg/cli/generate.go, pkg/cli/gleaner.go, pkg/cli/nabu.go, pkg/cli/root.go, pkg/cli/setup.go
=> Dv repologger

go.mod, pkg/cli/nabu.go, pkg/cli/object.go, pkg/cli/prefix.go, pkg/cli/prune.go
could roll back the go version. Updated when I was trying to figure out why mime was not working
=> #113 fix missing mime definition

go.mod, go.sum, internal/config/sources.go, internal/summoner/acquire/headlessNG.go, internal/summoner/acquire/jsonutils_test.go, pkg/cli/config.go, pkg/cli/generate.go, pkg/cli/nabu.go, pkg/cli/object.go, pkg/cli/prefix.go, pkg/cli/prune.go
#115 generate a separate nabu_prov file for a prov bucket
no prov loaded into main graph by default
=> glcon generate nabu prov file

Makefile
I'm trying a private image out (pushed to my own Docker repo) right now and  it's working great. I'll edit the GitHub action here too, if this looks good.
=> M2 / ARM builds

VERSION, internal/common/logger.go, internal/summoner/acquire/acquire.go, internal/summoner/acquire/headlessNG.go
* logging in summon now uses withFields (url, issue) json will have url field in many lines.
* logging of the repository information only to files, not console (sent to /dev/null)
=> Logging changes

cmd/gleaner/main.go, cmd/husker/main.go, internal/common/logger.go, internal/config/minio.go, internal/config/sources.go, internal/summoner/acquire/acquire.go, internal/summoner/acquire/delaythread.go, internal/summoner/acquire/prov.go
=> dont panic because an issue with prov

internal/common/logger.go, internal/common/stats.go, internal/summoner/summoner.go
Output runstats to a file, and be sure that even if the process is stopped, that file is written.
=> runstats is output even if ctl-C is hit

internal/common/calcShaNorm.go, internal/common/identifier.go, internal/common/identifier_test.go, internal/common/testdata/identifier/jsonGraphWifire.json, internal/common/testdata/identifier/jsonId.json, internal/common/testdata/identifier/jsonIdPaths.json, internal/common/testdata/identifier/jsonIdentifierArrayMultiple.json, internal/common/testdata/identifier/jsonIdentifierArraySingle.json, internal/common/testdata/identifier/jsonIdentifierGraph.json, internal/common/testdata/identifier/jsonIdentifierObjectPath.json, internal/common/testdata/identifier/jsonIdentifierPath.json, internal/common/testdata/identifier/problemChildIris.json, internal/common/testdata/identifier/problemChildOpentop.json
Added ability to just generate a sha of the json.
Was option, but not coded.
=> Cleaned up tests. Files now used.

cmd/gleaner/main.go, internal/check/check.go, pkg/cli/check.go, pkg/cli/gleaner.go, pkg/cli/setup.go, pkg/gleaner.go, resoruces/configs/gleaner_bad
Adds check to see that minio connectivity exists
=> cli check minio command

.github/workflows/docker-dev.yml, .github/workflows/docker.yml
Use the matrix to build linux/amd64 and linux/arm containers
not sure if cpu correct version of gleaner is baked into container.
=> docker dev matrix

.github/workflows/docker.yml, build/Dockerfile_glcon, go.mod, go.sum
=> Dev docker glcon

configs/template/localConfig.yaml, internal/config/gleanerConfig.go, internal/config/localConfig.go, internal/config/minio.go, internal/config/sources.go
=> add region to generate minio. update template

.github/workflows/docker_glcon.yml, .github/workflows/docker_gleaner.yml, build/Dockerfile, build/Dockerfile_glcon
Multiple platform builds in docker.
Add schema.org into docker container at /assets
=> Dev docker multipleimage
